version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-fpm-buster
      - image: circleci/mysql:8.0.4
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_DATABASE: laravel_namiya 
    environment:
      APP_ENV: testing
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_namiya 
      DB_USERNAME: phper
      DB_PASSWORD: secret 

    steps:
      - checkout
      - run: sudo composer self-update --1
      - run: composer install -n --prefer-dist
      - run:
        name: npm ci
        command: |
          if [ ! -d node_modules ]; then
            npm ci
          fi 
      - run: npm run dev
      - run:
          name: get ready for postgres
          command: |
            sudo apt-get update
            sudo apt-get install libpq-dev
            sudo docker-php-ext-install pdo_mysql
            dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: sudo apt update
      - run: sudo docker-php-ext-install pdo_mysql

      - run: vendor/bin/phpunit